### ISSUE TITLE
VK-Blocks crashes when used with WP 5.9.1

### ISSUE THREAD

**Issue by apchristie** [vektor-inc/vk-blocks#101]
WordPress version 5.9.1
Current theme: Lightning (version 14.17.5)
Current plugin: VK Blocks (version 1.27.5)
PHP version 8.0.13

An error of type E_ERROR was caused in line 78 of the file C:\xampp\apps\wordpress\htdocs\wp-content\plugins\vk-blocks\vendor\composer\autoload_real.php. Error message: Uncaught Error: Failed opening required 'C:\xampp\apps\wordpress\htdocs\wp-content\plugins\vk-blocks\vendor\composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\apps\wordpress\htdocs\wp-content\plugins\vk-blocks\vendor\composer\autoload_real.php:78
Stack trace:
#0 C:\xampp\apps\wordpress\htdocs\wp-content\plugins\vk-blocks\vendor\composer\autoload_real.php(61): composerRequiree1ce4415ca15d3060dc228881621cfeb('6124b4c8570aa39...', 'C:\\xampp\\apps\\w...')
#1 C:\xampp\apps\wordpress\htdocs\wp-content\plugins\vk-blocks\vendor\autoload.php(7): ComposerAutoloaderInite1ce4415ca15d3060dc228881621cfeb::getLoader()
#2 C:\xampp\apps\wordpress\htdocs\wp-content\plugins\vk-blocks\vk-blocks.php(22): require_once('C:\\xampp\\apps\\w...')
#3 C:\xampp\apps\wordpress\htdocs\wp-settings.php(418): include_once('C:\\xampp\\apps\\w...')
#4 C:\xampp\apps\wordpress\htdocs\wp-config.php(110): require_once('C:\\xampp\\apps\\w...')
#5 C:\xampp\apps\wordpress\htdocs\wp-load.php(50): require_once('C:\\xampp\\apps\\w...')
#6 C:\xampp\apps\wordpress\htdocs\wp-login.php(12): require('C:\\xampp\\apps\\w...')
#7 {main}
 thrown

**Comment by kurudrive** [comment]
@apchristie 

Sorrry

I already fixed it .
Please re install again!
