### ISSUE TITLE
ボタンブロックに固定文字列のidが挿入されています

### ISSUE THREAD

**Issue by segayuu** [vektor-inc/vk-blocks#69]
いつもありがとうございます。
ボタンブロック内のaタグ全てにid="vk_button_link"が挿入されています。
このため、1ページ内に複数のボタンブロックを使用した場合、一意でないidが存在することになります。
idをなくすこと、あるいは重複しないように実装することは可能でしょうか。

**Comment by kurudrive** [comment]
ご報告ありがとうございます。
修正まで今しばらくお待ちください。

**Comment by segayuu** [comment]
返信ありがとうございます。
ゆっくりコード見ててid周りが非推奨設定済みだったことを理解しました。
新たに作成する場合はすでに発生しません。
古いバージョンから使用していて、それが気になる場合に、記事更新によってブロック再構築が必要、という自己解決でした。
