### ISSUE TITLE
リストブロックのスタイルで、数字-四角 だと続きの文字との間隔がほとんど無い

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks#76]
![list-bug](https://user-images.githubusercontent.com/3272660/100581142-8fd9f100-332a-11eb-8cfd-fdbc53a8ed53.png)

**Comment by goutetsuguma** [comment]
【1系修正】プルリクを出しましたのでご確認お願い致します。
https://github.com/vektor-inc/vk-blocks-pro/pull/236
