### ISSUE TITLE
新FAQブロック挿入時にNoticeが出る

### ISSUE THREAD

**Issue by mypacecreator** [vektor-inc/vk-blocks#80]
デバッグモード下で新FAQブロックを挿入すると以下のNoticeが出ます。

```
Notice: Undefined index: new_faq_accordion in /{path}/wp-content/plugins/vk-blocks/src/blocks/faq2/index.php on line 24

Notice: Undefined index: new_faq_accordion in /{path}/wp-content/plugins/vk-blocks/src/blocks/faq2/index.php on line 26
```

おそらく、Pro版にしかないアコーディオン機能のオプション項目の設定内容を、無料版のときも見に行っているのではないでしょうか？

無料版バージョン 1.2.1、デフォルトテーマ適用、他プラグインOFF状態で確認。

**Comment by kurudrive** [comment]
ふぁー、ありがとうございますー！

**Comment by kurudrive** [comment]
@drill-lancer さんが作業して、 @shimotmk さんに情報共有するか、
無料版とプロ版の構成処理などを @drill-lancer さんが @shimotmk さんに説明して作業してもらうか、
@drill-lancer さんのお好みで対応よろしくお願いいたします。

**Comment by kurudrive** [comment]
@drill-lancer これリリース済みですよね？

**Comment by drill-lancer** [comment]
ですね。だからクローズしました。

**Comment by kurudrive** [comment]
@mypacecreator
おまたせしました。修正版リリース済みですのでお時間のある時に確認よろしくお願いいたします。

**Comment by mypacecreator** [comment]
@kurudrive 直っていることを確認しました！ありがとうございます！
