### ISSUE TITLE
ページネーションのマージンはiPhoneのガイドライン(44px 以上)に沿って欲しい

### ISSUE THREAD

**Issue by shimotmk** [vektor-inc/vk-blocks#81]

**Comment by drill-lancer** [comment]
えーと、キャプチャー画面って貼れたりします？
思い描いている解釈があってるかどうか不安なので・・・

**Comment by drill-lancer** [comment]
下記に移動しました
https://github.com/vektor-inc/vk-blocks-pro/issues/595
