### ISSUE TITLE
リストブロックのアイコンの色を任意の色に指定できるようにしたい。あるいはせめてキーカラーにしたい。

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks#83]
毎回思いつつ先送りしてるので確かパレット前とっかえとか、ブロック毎にCSSを出力するのがちょっと事故りやすいとか理由があったはず。

5.8 の theme.json で考える

**Comment by ChiakiKouno** [comment]
リストアイコンの色設定に、カスタムカラーパレットに対応したい、のIssueを立てようとしましたら、こちらがきっと同じですよね。

**Comment by ChiakiKouno** [comment]
パターンライブラリで使用することが増えてきそうなので、ちょこっとリマインド。

**Comment by kurudrive** [comment]
実装リリース済み close
