### ISSUE TITLE
枠線ボックス :last-child 要素のmargin-bottom を 0 にしないと無駄に余白ができる → 余白の説明追加

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks#86]
![絞り込み検索プラグイン-VK-Filter-Search-デモサイト-名古屋でお部屋探しはベクトルにおまかせ](https://user-images.githubusercontent.com/3272660/117745551-a7a49200-b245-11eb-9171-4d705f9efab3.png)

たぶん枠線の 最後の要素の margin-bottom を0にすればいい感じになるはず。
※ 編集画面ではDOM構造が違うので、別途対応しないといけないが、もしかしたら構造上無理かもしれない。

**Comment by shimotmk** [comment]
@kurudrive 
こちらのissueを見てみたのですが、これは枠線ブロックのCSSではなくVK Filter Searchのフォームのmargin-bottomが原因な様です
テストページ：https://demo.dev3.biz/vk-filter-search/test/

VK Filter Searchのformのmargin-bottom を0に調整するということでよろしいでしょうか？

**Comment by kurudrive** [comment]
@shimotmk いえ、Filter Search に限らず、pタグや Hタグで終わってもそれぞれ margin-bottom がついてるので、個別に対応とかやってられないので、枠線ブロックに対して、中に入っている要素の最後の要素の margin-bottom を削除する CSS を追加する想定です。

**Comment by kurudrive** [comment]
枠線ブロックのインナー部分のクラス名:last-child{
margin-bottom:0;
}

にすればいけるんじゃないかと適当に期待。

**Comment by shimotmk** [comment]
@kurudrive 
ありがとうございます
枠線ブロックの中の最後の要素は一律でmargin-bottom を0にするということですね🙇‍♂️
承知いたしました！

**Comment by kurudrive** [comment]
@shimotmk あ、これあと上も同じだ。

**Comment by kurudrive** [comment]
[ 余白 ]

枠線ブロック内の最初の要素の margin-top と 最後の要素の margin-bottom は自動的に0になります。
最初と最後に余白をつけたい場合はスペーサーブロックなどで margin指定ではなくheight指定でご利用ください。

**Comment by kurudrive** [comment]
[ 余白 ] ← 右側のパネル名

↓ 展開した時に表示される文章

枠線ブロック内の最初の要素の margin-top と 最後の要素の margin-bottom は自動的に0になります。
最初と最後に余白をつけたい場合はスペーサーブロックなどで margin指定ではなくheight指定でご利用ください。

**Comment by kurudrive** [comment]
@shimotmk こちらマージ済みなのでcloseしますー！
ありがとうございましたー！
