### ISSUE TITLE
文章の途中で小さい文字や大きい文字を入力できるようにしたい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks#87]
※ 無料版にも反映するので無料版のリポジトリに書いてますが 作業は Pro 版リポジトリで実装よろしくお願いいたします。

文章の途中で一部だけ小さいしたり大きくしたい場面がある。

既存の蛍光マーカーみたいな実装でいけるのではないかと思います。

サイズは本文の文字のサイズ選択（段落ブロックなど）と同じ選択肢で。
多分同じクラス名などが使えるのではないかなと。

詳細な仕様までは考えてないので

* 適当に考えて実装前に確認する
* 適当に実装して見せる

の何れかでよろしくお願いいたします。

**Comment by drill-lancer** [comment]
https://developer.wordpress.org/block-editor/reference-guides/components/font-size-picker/

**Comment by drill-lancer** [comment]
@kurudrive 
名前は vk-font-size あたりが無難でしょうか？
代案あったりします？

**Comment by kurudrive** [comment]
@drill-lancer 何の名前？

**Comment by drill-lancer** [comment]
@kurudrive 
このフォーマットの名前かつフォルダ名です。

**Comment by kurudrive** [comment]
@drill-lancer 
他で使ってる形式を踏襲してください。
nowrapやhighlighterなどが vk- はつけてないので vk はなくて良いです。
font-size だけだと 通常のフォントサイズとの区別などがわかりにくいので、
inline-font-size にしてください。

**Comment by drill-lancer** [comment]
@kurudrive 
了解しました。
inline-font-size を採用します。
（パッと名前が思いつかなかったので相談しました。）

**Comment by kurudrive** [comment]
@goutetsuguma 
アイコン待ち
※ そんなに急ぎではないので無理やりこっちの作業を優先する必要はありません。

**Comment by goutetsuguma** [comment]
@kurudrive 
アイコン追加いたしました。ご確認お願いいたします

関連するプルリク
https://github.com/vektor-inc/vk-blocks-pro/pull/503

**Comment by kurudrive** [comment]
@goutetsuguma ありがとうございます！
ちょっと大きい方のAが A と認識するのが難しいので 文字サイズの変更だと認識しにくいかなと感じました。

**Comment by goutetsuguma** [comment]
@kurudrive 修正いたしましたので、お手隙の際にご確認お願いいたｈしますmm

**Comment by kurudrive** [comment]
@goutetsuguma |・ｗ・）.oO（ さ、作業は平日の昼間でええんやで... ）
