### ISSUE TITLE
見出しブロックを VK Blocks の見出しにコンバートできるようにしたい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks#88]
通常本文を書く時には ## 見出し などで入力するが、アイコンフォントを使いたい時には VK Blocks の見出しブロックを使う事になるので、標準ブロックの p から h に切り替えるみたいに切り替えできるようにしたい。

**Comment by drill-lancer** [comment]
https://developer.wordpress.org/block-editor/reference-guides/block-api/block-transforms/

**Comment by kurudrive** [comment]
@drill-lancer ありがとうございました！
昨日リリースしました！
