### ISSUE TITLE
VKBLOCKSボタンの管理画面から見た時の表示崩れについて

### ISSUE THREAD

**Issue by kei848** [vektor-inc/vk-blocks#90]
Lightning 機能設定の世代設定を変更してしまった影響か、何かしらのプラグイン更新の影響かにより
管理画面（編集画面）のからもともと使用していたVKBLOCKSのボタンが崩れた表示であらわれている。
プレビューや実サイトでは表示は問題ないが、戻し方等お分かりであればご教示ください。

**Comment by kurudrive** [comment]
現行版で問題ないと思いますので close します。
また不具合出ましたらよろしくお願いいたします。
