### ISSUE TITLE
見出しスタイルに左右線を選択時、一部文字に「テキスト色」を指定すると、display:flexとなってスマホ表示で崩れてしまう

### ISSUE THREAD

**Issue by ChiakiKouno** [vektor-inc/vk-blocks#93]
VK Blocks ver.1.20.4 + Katawara で見つけました。

![スクリーンショット 2021-12-06 午後11 30 43](https://user-images.githubusercontent.com/43702482/144878411-d41a78d4-d3f8-4c83-8886-834aa1047573.png)

**Comment by goutetsuguma** [comment]
ありがとうございます！おそらくこちらと同じ症状のようなきがします
https://github.com/vektor-inc/vk-blocks-pro/issues/911

**Comment by ChiakiKouno** [comment]
おお、同じっぽいです！すみません気づきませんでした、ありがとうございます＾＾
